name: Yahtzee testing workflow

on: 
  workflow_dispatch:
    inputs:
      tests:
        required: true
        default: all
        type: choice
        description: Tags to run
        options: 
        - all
        - playerName
        - die
        - smoke

jobs: 
  api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checkout the this repository.
      - name: Checkout
        uses: actions/checkout@v4

      - name: build application image
        run: docker build -t yahtzee:latest .

      - name: run application
        run:  docker run -d -p 8080:8080 yahtzee:latest

      - name: Install dependencies
        working-directory: ./yahtzee-tests
        run: npm ci
      
      - name: Run All Playwright tests
        working-directory: ./yahtzee-tests
        if: github.event.inputs.tests == 'all'
        run: npx playwright test

      - name: Run @Tagged Playwright tests
        working-directory: ./yahtzee-tests
        if: github.event.inputs.tests != 'all'
        run: npx playwright test --grep "${{ github.event.inputs.tests }}"   
        
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: yahtzee-tests/playwright-report/
      
